# Generated by Django 5.2.7 on 2025-12-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Código del Documento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content_html', models.TextField(verbose_name='Contenido HTML')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
