# Generated by Django 5.2.7 on 2025-11-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Dispositivo')),
                ('device_identifier', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Identificador Único')),
                ('is_lost', models.BooleanField(default=False, verbose_name='Reportado como perdido')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Última vez visto')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['user', 'name'],
            },
        ),
    ]
