# Generated by Django 5.2.7 on 2025-11-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_visible_to_contacts',
            field=models.BooleanField(default=True, verbose_name='Visible para contactos de confianza'),
        ),
    ]
